apiVersion: v1
kind: Service
metadata:
  name: hamm-notifications-svc
  namespace: notifications
spec:
  selector:
    app: hamm-notifications
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP